version: '3.8'

services:
  glms_app:
    build: .
    container_name: glms_phoenix_app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./db.json:/app/db.json
    environment:
      - PORT=8080
